export const TOPICS = [
  {
    id: 1,
    slug: 'combinatorial-optimisation',
    title: 'Combinatorial Optimisation',
    subtitle: 'When there are too many possibilities to check',
    color: '#3B82F6',
    group: 'Foundations',
  },
  {
    id: 2,
    slug: 'heuristic-search',
    title: 'Heuristic Search',
    subtitle: 'Climbing toward a solution, one step at a time',
    color: '#3B82F6',
    group: 'Foundations',
  },
  {
    id: 3,
    slug: 'metaheuristics',
    title: 'Metaheuristics',
    subtitle: 'Strategies for escaping the traps',
    color: '#8B5CF6',
    group: 'Search strategies',
  },
  {
    id: 4,
    slug: 'move-acceptance',
    title: 'Move Acceptance & Parameter Tuning',
    subtitle: 'How algorithms decide to accept a worse solution',
    color: '#8B5CF6',
    group: 'Search strategies',
  },
  {
    id: 5,
    slug: 'evolutionary-algorithms-1',
    title: 'Evolutionary Algorithms',
    subtitle: 'How populations evolve toward better solutions',
    color: '#10B981',
    group: 'Evolutionary',
  },
  {
    id: 6,
    slug: 'evolutionary-algorithms-2',
    title: 'Evolutionary Algorithms II',
    subtitle: 'Memes, permutations, and self-adaptation',
    color: '#10B981',
    group: 'Evolutionary',
  },
  {
    id: 7,
    slug: 'hyper-heuristics-1',
    title: 'Hyper-heuristics',
    subtitle: 'Algorithms that choose algorithms',
    color: '#F59E0B',
    group: 'Hyper-heuristics',
  },
  {
    id: 8,
    slug: 'hyper-heuristics-2',
    title: 'Hyper-heuristics II',
    subtitle: 'Generating heuristics with genetic programming',
    color: '#F59E0B',
    group: 'Hyper-heuristics',
  },
  {
    id: 9,
    slug: 'fuzzy-systems',
    title: 'Fuzzy Systems',
    subtitle: 'Logic that handles degrees of truth',
    color: '#F43F5E',
    group: 'Special topics',
  },
  {
    id: 10,
    slug: 'agent-based-modelling',
    title: 'Agent-Based Modelling',
    subtitle: 'Emergent behaviour from simple rules',
    color: '#F43F5E',
    group: 'Special topics',
  },
  {
    id: 11,
    slug: 'large-language-models',
    title: 'Large Language Models',
    subtitle: 'From next-token prediction to agentic AI',
    color: '#F43F5E',
    group: 'Special topics',
  },
]
